### ISSUE TITLE
django-static-version vs ManifestStaticFileStorage

### ISSUE THREAD

**Issue by mixxorz** [MetaMetricsInc/django-static-version#1]
Hey there,

Is there any advantage to using query based (`domain.com/static/main.css?v=1.0`) to file hashes (`domain.com/static/main.55e7cbb9ba48.css`)? Django's [ManifestStaticFileStorage](https://docs.djangoproject.com/en/1.10/ref/contrib/staticfiles/#manifeststaticfilesstorage) uses the file's hash so that any time the file is changed, it will have a different hash in the name.

**Comment by pkonneker** [comment]
There's definitely a lot of different ways to do cache busting.

We specifically want to replace files in s3 as opposed to keeping different versions around. Cloudfront caches things by the query strings, so just upgrading the version number being requested will trigger the updated version being cached like we want without much fuss. This method keeps things really simple. The only thing I'm aware of us giving up is quick/easy rollback.

So I'd say no real advantage, no. It's just a different way of doing things to fit our use case.

**Comment by mixxorz** [comment]
I didn't realize that's how Cloudfront's caches work. Interesting. Thanks!
